FROM centos:7 
RUN yum -y install httpd 
CMD ["apachectl","-DFOREGROUND"]

## docker run -it --name -p xx:xx nom_imagen:tags

## docker run -d --name -p xx:xx nom_imagen:tags

##--name 

## docker build -t nom_imagen:tags

#nom_imagen:dev-1.0.0
#nom_imagen:1.0.0